name: Pipelines

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Frontend CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Deploy frontend to EC2
        run: |
          ssh ubuntu@52.205.32.200 "mkdir -p ~/frontend/"
          scp -r frontend/build/* ubuntu@52.205.32.200:~/frontend/
  backend:
    name: Backend CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install backend dependencies
        run: pip3 install -r requirements.txt
        working-directory: backend

      - name: Run backend tests
        run: pytest
        working-directory: backend

      - name: Deploy backend to EC2
        run: |
          ssh ubuntu@34.237.64.250 "mkdir -p ~/backend/"
          scp -r backend/* ubuntu@34.237.64.250:~/backend/

  # You can add more jobs for other tasks if needed
